# List of brew commands to run to install a bunch of packages
#
# Can be executed by running 'brew bundle'
#
# Cleanup
# 'brew cleanup -ns' to list items that will be removed
# 'brew cleanup -s' to actually remove them

# Common packanges to install
brew "git"
brew "tmux"
brew "fzf"
brew "fd"
brew "bat"
brew "ripgrep"

# Platform dependent packages
if OS.mac?
    brew "macvim"
    brew "coreutils"
    brew "gnu-sed"

    cask "rectangle"
    cask "flux"
else
    brew "vim"
end
