#!/bin/sh

# Install Homebrew

# Prevent Chef from overriding /user/local ownership
# sudo touch /Library/CPE/tags/homebrew

BASE_DIR="$(cd "$(dirname "$0")"; pwd)";

if ! type brew >/dev/null 2>&1; then
	echo "Installing Homebrew!"
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

	brew bundle -v --file="$BASE_DIR/Brewfile"
else
	echo "Homebrew already installed"
fi
