# ===== Zsh Configuration =====

# zsh help documentation:
#   These configuration files contain comments of the form: #<letter>#
#   These special markers are used to automatically generate help lines
#   for various things directly from the configuration files themselves.
#
# List of tags used:
#   #a#     Alias that should be included in 'help-aliases'
#   #f#     Function that should be included in 'help-functions'
#   #k#     Keybinding that should be included in 'help-zle'

# ---- zsh profiling --------------------------------------------------

# execute 'ZSH_PROFILE_RC=1 zsh' or 'profile' and run 'zprof' for details
if [[ $ZSH_PROFILE_RC -gt 0 ]] ; then
    zmodload zsh/zprof
fi

function profile () {
    ZSH_PROFILE_RC=1 zsh "$@"
}

# ---- general configuration ------------------------------------------

setopt LONG_LIST_JOBS # display PID when suspending processes
setopt MULTIOS

# report about cpu-/system-/user-time of command if running longer than
# 5 seconds
REPORTTIME=5

if [[ "$OSTYPE" == darwin* ]]; then
    export BROWSER='open'
fi

export EDITOR=vim
export VISUAL=vim
# ignore case, exit if it fits on one screen, allow colors for ls and grep
export LESS="-iFXR"
export PAGER=less

# Remove duplicate entries from PATH
typeset -aU path

# Add personal Scripts to PATH
path=( $HOME/bin $HOME/dotfiles/bin $path)

# Load all config files in .zsh
for file in ${ZDOTDIR}/*.zsh; do
    source $file
done
unset file

# Enable FZF completion
# [Ctrl-T] paste the selected file path(s) into the command line
# [Alt-C]  cd into the selected directory
# [Ctrl-R] paste the selected command from history into the command line
# [**] fzf completion trigger, e.g. 'ls **<Tab>'
# - $FZF_TMUX               (default: 0)
# - $FZF_TMUX_HEIGHT        (default: '40%')
# - $FZF_COMPLETION_TRIGGER (default: '**')
# - $FZF_COMPLETION_OPTS    (default: empty)
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# ---- local overrides ------------------------------------------------

# Use '~/.zshrc.local' file for machine dependent modifications
[ -f ~/.zshrc.local ] && source ~/.zshrc.local
