# .bashrc File

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.bash_prompt is used to setup the prompt $PS1
# * ~/.aliases is used to store aliases
for file in ~/.{path,bash_prompt,aliases}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Setup PATH
# Add personal Scripts to PATH
PATH=$PATH:/$HOME/dotfiles/bin

# Setup Aliases
alias ls="ls -G"

#export LSCOLORS="ExGxBxDxCxEgEdxbxgxcxd"
#export CLICOLOR=1
#export LSCOLORS=Gxfxcxdxbxegedabagacad


# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Add tab completion for `defaults read|write NSGlobalDomain`
# You could just use `-g` instead, but I like being explicit
complete -W "NSGlobalDomain" defaults

# Add `killall` tab completion for common apps
complete -o "nospace" -W "Contacts Calendar Dock Finder Mail Safari iTunes SystemUIServer Terminal Twitter" killall

# Autocomplete git commands
if [ -f $(brew --prefix)/etc/bash_completion.d/git-completion.bash ]; then
    . $(brew --prefix)/etc/bash_completion.d/git-completion.bash
fi

# Add tab completon for many Bash commands
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;
