# .bashrc File

# Setup PATH
# Add personal Scripts to PATH
PATH=$PATH:/$HOME/dotfiles/bin

# Setup prompt
NORMAL="\[\e[0m\]"
RED="\[\e[1;31m\]"
GREEN="\[\e[1;32m\]"
BLUE="\[\e[0;34m\]"
PURPLE="\[\e[0;35m\]"
CYAN="\[\e[0;36m\]"
PS1="$RED\u$NORMAL@$CYAN\h $RED[ $NORMAL\w$RED ]\$ $NORMAL"

# Setup Aliases
alias ls="ls -G"

#export LSCOLORS="ExGxBxDxCxEgEdxbxgxcxd"
#export CLICOLOR=1
#export LSCOLORS=Gxfxcxdxbxegedabagacad


# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Add tab completion for `defaults read|write NSGlobalDomain`
# You could just use `-g` instead, but I like being explicit
complete -W "NSGlobalDomain" defaults

# Add `killall` tab completion for common apps
complete -o "nospace" -W "Contacts Calendar Dock Finder Mail Safari iTunes SystemUIServer Terminal Twitter" killall

# Autocomplete git commands
[ -f ~/.git-completion.bash ] && source ~/.git-completion.bash
