#!/usr/bin/env bash

#####################################################################
#   bash_prompt                                                     #
#   Sets up the bash prompt env variable PS1                        #
#                                                                   #
#   Author: Brandon Williams                                        #
#####################################################################

# If the terminal supports 256 colors enable 256color
if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
	export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
	export TERM=xterm-256color
fi

# set up the colors that will be used for the prompt
if tput setaf 1 &> /dev/null; then
    # use the following if if there aren't 256 colors?
	# if [[ $(tput colors) -ge 256 ]] 2>/dev/null; then

	tput sgr0; # reset colors
	bold=$(tput bold);
	reset=$(tput sgr0);

	# Solarized colors, taken from http://git.io/solarized-colors.
	black=$(tput setaf 0);
	blue=$(tput setaf 33);
	cyan=$(tput setaf 37);
	green=$(tput setaf 64);
	orange=$(tput setaf 166);
	purple=$(tput setaf 125);
	red=$(tput setaf 124);
	violet=$(tput setaf 61);
	white=$(tput setaf 15);
	yellow=$(tput setaf 136);
else
	bold='';
	reset="\e[0m";
	black="\e[1;30m";
	blue="\e[1;34m";
	cyan="\e[1;36m";
	green="\e[1;32m";
	orange="\e[1;33m";
	purple="\e[1;35m";
	red="\e[1;31m";
	violet="\e[1;35m";
	white="\e[1;37m";
	yellow="\e[1;33m";
fi;

# Highlight the user name when logged in as root.
if [[ "${USER}" == "root" ]]; then
	userStyle="${red}";
else
	userStyle="${orange}";
fi;

# Highlight the hostname when connected via SSH.
if [[ "${SSH_TTY}" ]]; then
	hostStyle="${bold}${red}";
else
	hostStyle="${yellow}";
fi;

# Set the terminal title and prompt.
#PS1="\[\033]0;\W\007\]"; # working directory base name
#PS1+="\[${bold}\]\n"; # newline
#PS1+="\[${userStyle}\]\u"; # username
#PS1+="\[${white}\] at ";
#PS1+="\[${hostStyle}\]\h"; # host
#PS1+="\[${white}\] in ";
#PS1+="\[${green}\]\w"; # working directory full path
#PS1+="\$(prompt_git \"\[${white}\] on \[${violet}\]\" \"\[${blue}\]\")"; # Git repository details
#PS1+="\n";
#PS1+="\[${white}\]\$ \[${reset}\]"; # `$` (and reset color)
#export PS1;

# Set the continuation interactive prompt
#PS2="\[${yellow}\]→ \[${reset}\]";
#export PS2;

# Setup prompt
NORMAL="\[\e[0m\]"
RED="\[\e[1;31m\]"
GREEN="\[\e[1;32m\]"
BLUE="\[\e[0;34m\]"
PURPLE="\[\e[0;35m\]"
CYAN="\[\e[0;36m\]"
PS1="$RED\u$NORMAL@$CYAN\h $RED[ $NORMAL\w$RED ]\$ $NORMAL"
